formatter: markdown table

recursive:
  enabled: true
  path: modules

settings:
  anchor: false
  escape: false
  indent: 4

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->

    {{ .Content }}

    <!-- END_TF_DOCS -->
