formatter: markdown table

settings:
  anchor: false
  escape: false
  indent: 4

output:
  file: ../../README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_VPCE_DOCS -->

    {{ .Content }}

    <!-- END_TF_VPCE_DOCS -->
